ln -s error-only-openssl.txt error-only-openssh-sshd.txt
ln -s error-only-openssl.txt error-only-openssh-scp.txt
ln -s error-only-openssl.txt error-only-openssh-ssh-agent.txt
ln -s error-only-openssl.txt error-only-openssh-ssh-add.txt
ln -s error-only-openssl.txt error-only-openssh-ssh.txt
ln -s error-only-openssl.txt error-only-openssh-ssh-sk-helper.txt
ln -s error-only-openssl.txt error-only-openssh-ssh-pkcs11-helper.txt
ln -s error-only-openssl.txt error-only-openssh-sftp.txt
ln -s error-only-openssl.txt error-only-openssh-sftp-server.txt
ln -s error-only-openssl.txt error-only-openssh-ssh-keygen.txt
ln -s error-only-openssl.txt error-only-openssh-ssh-keyscan.txt
ln -s error-only-openssl.txt error-only-openssh-ssh-keysign.txt
